# SwiftLint configuration for SwiftIMAP

included:
  - Sources
  - Tests

excluded:
  - .build
  - .swiftpm
  - Package.swift

analyzer_rules:
  - unused_import
  - unused_declaration

opt_in_rules:
  - anyobject_protocol
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - enum_case_associated_values_count
  - explicit_init
  - fatal_error_message
  - file_header
  - file_name_no_space
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - function_default_parameter_at_end
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - operator_usage_whitespace
  - optional_enum_case_matching
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_action
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - trailing_closure
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

disabled_rules:
  - todo
  - trailing_whitespace
  - line_length

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 500
  error: 1200

function_body_length:
  warning: 40
  error: 100

function_parameter_count:
  warning: 6
  error: 8

large_tuple:
  warning: 3
  error: 4

cyclomatic_complexity:
  warning: 15
  error: 25

nesting:
  type_level:
    warning: 2
  function_level:
    warning: 3

identifier_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 40
    error: 50
  excluded:
    - id
    - to
    - cc
    - ok
    - no

custom_rules:
  no_print_statements:
    name: "No Print Statements"
    regex: '^\s*print\('
    message: "Use the Logger instead of print statements"
    severity: warning